name: sport_news
description: Related sport news application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #assets
  google_fonts: ^2.1.0

  #firebase
  #firebase_messaging: ^10.0.0
  #firebase_database: 6.1.2
  cloud_firestore:
  firebase_analytics:
  firebase_auth:
  firebase_storage:
  #firebase_crashlytics: ^0.1.4+1
  flare_flutter: ^2.0.6

  #widgets
  fluid_layout: ^0.1.0
  step_progress_indicator: ^1.0.0
  feature_discovery: ^0.14.0
  flutter_staggered_animations: "^1.0.0"
  equatable: ^2.0.0
  #ui \ code
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  auto_size_text: ^2.1.0
  url_launcher: ^6.0.4
  oktoast: ^3.0.0
  stream_transform: ^2.0.0
  shared_preferences: ^2.0.5
  rx_shared_preferences: ^2.1.0

  #other
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.22.0
  extended_image: ^4.1.0
  flutter_swiper: ^1.1.6
  flutter_widget_from_html_core: ^0.6.1+1
  streams_channel: 0.3.0
  flutter_inappwebview: ^5.3.2
  #deeplinks
  #facebook_deeplinks: ^0.1.0
  flutter_facebook_app_links: ^1.1.1+4
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/drawable/
    - assets/icons/menu_news_icon.svg
    - assets/animations/News.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SportNewsIcons
      fonts:
        - asset: assets/fonts/SportNewsIcons.ttf
    - family: SFCompactDisplay
      fonts:
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SanFrancisco/SF-Compact-Display-Black.otf
          weight: 900
    # - family: SFCompactRounded
    #   fonts:
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Ultralight.otf
    #       weight: 100
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Thin.otf
    #       weight: 200
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Light.otf
    #       weight: 300
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Semibold.otf
    #       weight: 600
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Heavy.otf
    #       weight: 800
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Rounded-Black.otf
    #       weight: 900
    # - family: SFCompactText
    #   fonts:
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Ultralight.otf
    #       weight: 100
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Thin.otf
    #       weight: 200
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Light.otf
    #       weight: 300
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Semibold.otf
    #       weight: 600
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Heavy.otf
    #       weight: 800
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-Black.otf
    #       weight: 900
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-UltralightItalic.otf
    #       weight: 100
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-ThinItalic.otf
    #       weight: 200
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-LightItalic.otf
    #       weight: 300
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-RegularItalic.otf
    #       weight: 400
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-MediumItalic.otf
    #       weight: 500
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-SemiboldItalic.otf
    #       weight: 600
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-BoldItalic.otf
    #       weight: 700
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-HeavyItalic.otf
    #       weight: 800
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Compact-Text-BlackItalic.otf
    #       weight: 900
    #       style: italic
    # - family: SFMono
    #   fonts:
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-Light.otf
    #       weight: 300
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-Semibold.otf
    #       weight: 600
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-Heavy.otf
    #       weight: 800
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-LightItalic.otf
    #       weight: 300
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-RegularItalic.otf
    #       weight: 400
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-MediumItalic.otf
    #       weight: 500
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-SemiboldItalic.otf
    #       weight: 600
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-BoldItalic.otf
    #       weight: 700
    #       style: italic
    #     - asset: assets/fonts/SanFrancisco/SF-Mono-HeavyItalic.otf
    #       weight: 800
    #       style: italic
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-ThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic
    # - family: SFProRounded
    #   fonts:
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Ultralight.otf
    #       weight: 100
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Thin.otf
    #       weight: 200
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Light.otf
    #       weight: 300
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Semibold.otf
    #       weight: 600
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Heavy.otf
    #       weight: 800
    #     - asset: assets/fonts/SanFrancisco/SF-Pro-Rounded-Black.otf
    #       weight: 900
    - family: SFProText
      fonts:
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-Black.otf
          weight: 900
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-ThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SanFrancisco/SF-Pro-Text-BlackItalic.otf
          weight: 900
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
