name: sport_news
description: Related sport news application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #assets
  google_fonts: ^2.1.0

  #firebase
  #firebase_messaging: ^10.0.0
  #firebase_database: 6.1.2
  cloud_firestore:
  firebase_analytics:
  firebase_auth: "^1.2.0"
  firebase_storage:
  #firebase_crashlytics: ^0.1.4+1
  flare_flutter: ^2.0.6

  #widgets
  fluid_layout: ^0.1.0
  step_progress_indicator: ^1.0.0
  feature_discovery: ^0.14.0
  flutter_staggered_animations: "^1.0.0"
  equatable: ^2.0.2
  #ui \ code
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  auto_size_text: ^2.1.0
  url_launcher: ^6.0.5
  oktoast: ^3.0.0
  stream_transform: ^2.0.0
  shared_preferences: ^2.0.6
  rx_shared_preferences: ^2.1.0

  #other
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.22.0
  extended_image: ^4.1.0
  flutter_swiper: ^1.1.6
  #flutter_widget_from_html_core: ^0.6.1+1
  streams_channel: 0.3.0
  flutter_inappwebview: ^5.3.2
  #deeplinks
  #facebook_deeplinks: ^0.1.0
  #flutter_facebook_app_links: ^1.1.1+4
  get:
  flutter_datetime_picker: ^1.5.1
  google_sign_in: ^5.0.4

dependency_overrides:
  
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/drawable/
    - assets/icons/menu_news_icon.svg
    - assets/animations/News.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:
   
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
